name = "AlignmentAlgorithms"
uuid = "3c894fce-1a5f-4a14-a547-781e8c68175f"
<<<<<<< HEAD
authors = ["Kevin Bonham, PhD", "Deniz Uzun"]
=======
authors = ["Kevin Bonham, PhD", "Ellie Gibbs", "Anika Luo"]
>>>>>>> main
version = "0.1.0"

[compat]
julia = "1.6"
